/*
 * Ververica Platform API
 *
 * The Ververica Platform APIs, excluding Application Manager.
 *
 * API version: 2.6.2
 * Contact: platform@ververica.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package platformapi

type Property struct {
	DefaultValue  string `json:"defaultValue,omitempty"`
	DefinesFormat bool   `json:"definesFormat,omitempty"`
	Description   string `json:"description,omitempty"`
	Key           string `json:"key,omitempty"`
	Required      bool   `json:"required,omitempty"`
}
