/*
 * Ververica Platform API
 *
 * The Ververica Platform APIs, excluding Application Manager.
 *
 * API version: 2.6.2
 * Contact: platform@ververica.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package platformapi

type VvpColumn struct {
	Expression string         `json:"expression,omitempty"`
	Meta       *VvpColumnMeta `json:"meta,omitempty"`
	Name       string         `json:"name,omitempty"`
	Type_      string         `json:"type,omitempty"`
}
