/*
 * Ververica Platform API
 *
 * The Ververica Platform APIs, excluding Application Manager.
 *
 * API version: 2.6.2
 * Contact: platform@ververica.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package platformapi

type VvpWatermark struct {
	TimeColumn          string `json:"timeColumn,omitempty"`
	WatermarkExpression string `json:"watermarkExpression,omitempty"`
	WatermarkType       string `json:"watermarkType,omitempty"`
}
